spring:
  liquibase:
    change-log: classpath:/data/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/affito
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
